In [24]:
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [6]:
with open('x_credit_risk.plk','rb') as f:
    x_credit_risk,y_credit_risk = pickle.load(f)

In [7]:
x_credit_risk = np.delete(x_credit_risk,[2,7,11], axis=0)

In [8]:
x_credit_risk

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [9]:
y_credit_risk = np.delete(y_credit_risk,[2,7,11], axis=0)
y_credit_risk

array(['alto', 'alto', 'alto', 'baixo', 'baixo', 'alto', 'baixo', 'baixo',
       'alto', 'baixo', 'alto'], dtype=object)

In [12]:
credit_risk_logistic_regression = LogisticRegression(random_state=1)
credit_risk_logistic_regression.fit(x_credit_risk,y_credit_risk)


LogisticRegression(random_state=1)

In [13]:
credit_risk_logistic_regression.intercept_

array([-0.80855152])

In [15]:
credit_risk_logistic_regression.coef_

array([[-0.76706797,  0.23921064, -0.47989768,  1.12196145]])

In [16]:
predict_risk_credit = credit_risk_logistic_regression.predict([[0,0,1,2],[2,0,0,0]])
predict_risk_credit

array(['baixo', 'alto'], dtype=object)

In [17]:
with open('x_credit.plk','rb') as g:
    x_credit_test,y_credit_test,x_credit_train,y_credit_train = pickle.load(g)

In [18]:
x_credit_test

array([[-1.3754462 ,  0.50630999,  0.10980934],
       [ 1.45826409, -1.64894017, -1.21501497],
       [-0.79356829,  0.22531104, -0.43370226],
       ...,
       [ 0.21738243, -0.14704491,  1.40872498],
       [ 0.58716195,  0.66435405,  0.67948086],
       [ 0.68315357,  0.04084859,  1.91819744]])

In [19]:
y_credit_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
credit_logistic_regression = LogisticRegression(random_state=1)
credit_logistic_regression.fit(x_credit_train,y_credit_train)

LogisticRegression(random_state=1)

In [21]:
credit_logistic_regression.intercept_

array([-4.9578298])

In [22]:
credit_logistic_regression.coef_

array([[-1.98730771, -2.82863217,  3.29006751]])

In [23]:
predict_credit = credit_logistic_regression.predict(x_credit_test)

In [25]:
accuracy_credit = accuracy_score(y_credit_test,predict_credit)
accuracy_credit

0.944

In [26]:
print(classification_report(y_credit_test,predict_credit))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97      1281
           1       0.85      0.74      0.80       219

    accuracy                           0.94      1500
   macro avg       0.91      0.86      0.88      1500
weighted avg       0.94      0.94      0.94      1500



In [27]:
with open('x_census.plk','rb') as m:
    x_census_test,y_census_test,x_census_train,y_census_train = pickle.load(m)

In [28]:
x_census_test

array([[-0.2444502 , -0.17429511, -0.26209736, ..., -0.14592048,
        -0.21665953,  0.28852962],
       [-0.2444502 , -0.17429511, -0.26209736, ..., -0.14592048,
        -0.21665953, -0.03542945],
       [-0.2444502 , -0.17429511, -0.26209736, ..., -0.14592048,
        -0.21665953, -0.03542945],
       ...,
       [-0.2444502 , -0.17429511, -0.26209736, ...,  0.89508344,
        -0.21665953, -0.03542945],
       [-0.2444502 , -0.17429511, -0.26209736, ..., -0.14592048,
        -0.21665953, -0.03542945],
       [-0.2444502 , -0.17429511, -0.26209736, ..., -0.14592048,
        -0.21665953, -0.03542945]])

In [29]:
y_census_test

22278     <=50K
8950      <=50K
7838      <=50K
16505     <=50K
19140      >50K
          ...  
21949      >50K
26405      >50K
23236      >50K
26823     <=50K
20721     <=50K
Name: income, Length: 9769, dtype: object

In [30]:
census_logist = LogisticRegression(random_state=1)
census_logist.fit(x_census_train,y_census_train)

LogisticRegression(random_state=1)

In [31]:
census_logist.intercept_

array([-2.10325542])

In [32]:
census_logist.coef_

array([[-7.44236861e-02,  1.29603755e-01, -2.43999366e-03,
        -6.59398172e-02,  6.18851374e-02,  4.16180161e-02,
        -8.63459461e-02, -6.89427194e-02, -1.23150406e-01,
        -9.39824864e-02, -1.54482878e-01, -2.12699778e-02,
        -3.33164963e-02, -4.52353641e-02, -9.41034260e-02,
        -8.80062822e-02, -8.99165792e-03,  7.45374356e-04,
         1.45882607e-01,  1.26379504e-01, -8.08870440e-02,
         1.48937801e-01, -1.97661217e-01,  1.18505670e-01,
         1.88314862e-02, -1.89805773e-01,  5.47921129e-02,
         6.93195996e-01, -4.51884018e-02, -5.23138137e-01,
        -9.58937665e-02, -8.33455244e-02, -7.84741788e-02,
        -8.10848829e-03, -2.21185326e-02,  1.72585106e-02,
         2.51641095e-01, -1.52725367e-01, -1.52260800e-01,
        -7.63046551e-02, -2.88151362e-01, -2.38787906e-01,
         1.69112324e-01,  8.23951925e-02,  8.81959893e-02,
         1.19441309e-01, -2.39774233e-02, -1.86205390e-02,
         1.20179445e-01, -9.00157579e-02, -2.92112431e-0

In [33]:
predict_census = census_logist.predict(x_census_test)

In [35]:
accuracy_census = accuracy_score(y_census_test,predict_census)
accuracy_census

0.8517760262053434

In [36]:
print(classification_report(y_census_test,predict_census))

              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      7407
        >50K       0.73      0.61      0.67      2362

    accuracy                           0.85      9769
   macro avg       0.81      0.77      0.79      9769
weighted avg       0.85      0.85      0.85      9769

