In [64]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

In [65]:
df_health_plan = pd.read_csv('../Bases de dados/plano_saude2.csv')
x_health_plan=df_health_plan.iloc[:,0:1].values
y_health_plan=df_health_plan.iloc[:,1].values

In [66]:
scaler_x = StandardScaler()
scaler_y = StandardScaler()
x_scaler = scaler_x.fit_transform(x_health_plan)
y_scaler = scaler_y.fit_transform(y_health_plan.reshape(-1,1))
x_scaler,y_scaler

(array([[-1.5666989 ],
        [-1.21854359],
        [-0.87038828],
        [-0.52223297],
        [-0.17407766],
        [ 0.17407766],
        [ 0.52223297],
        [ 0.87038828],
        [ 1.21854359],
        [ 1.5666989 ]]),
 array([[-0.72401136],
        [-0.7065653 ],
        [-0.66818397],
        [-0.59839975],
        [-0.48674498],
        [-0.35415495],
        [-0.17620517],
        [ 0.18667281],
        [ 0.8914935 ],
        [ 2.63609918]]))

In [67]:
neural_network_health = MLPRegressor(max_iter=1000)
neural_network_health.fit(x_scaler,y_scaler.ravel())

MLPRegressor(max_iter=1000)

In [68]:
neural_network_health.score(x_scaler,y_scaler)

0.9610522701186142

In [69]:
grafic = px.scatter(x=x_scaler.ravel(),y=y_scaler.ravel())
grafic.add_scatter(x=x_scaler.ravel(),y=neural_network_health.predict(x_scaler),name='Neural Network  Regression Health Plan')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
                           0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ]),
              'xaxis': 'x',
              'y': array([-0.72401136, -0.7065653 , -0.66818397, -0.59839975, -0.48674498,
                          -0.35415495, -0.17620517,  0.18667281,  0.8914935 ,  2.63609918]),
              'yaxis': 'y'},
             {'name': 'Neural Network  Regression Health Plan',
              'type': 'scatter',
              'x': array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
                           0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ]),
              'y': array([-0.72202802, -0.69578032, -0.65414105, -0.60138684, -0.53514592,
                          -0.42760545, -0.20426034,  0.36666771,  1.27873454,  2.19082127])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'y'}}}
})

In [70]:
new=[[40]]
new = scaler_x.transform(new)
new_predict = neural_network_health.predict(new)

In [71]:
scaler_y.inverse_transform(neural_network_health.predict(new).reshape(-1, 1))

array([[1095.66291579]])

In [72]:
df_houses = pd.read_csv('../Bases de dados/house_prices.csv')
x_houses = df_houses.iloc[:,3:19].values
y_houses = df_houses.iloc[:,2:3].values

In [73]:
x_houses_train,x_houses_test,y_houses_train,y_houses_test = train_test_split(x_houses,y_houses,random_state=1,test_size=0.3)

In [74]:
scales_x_houses = StandardScaler()
scales_y_houses = StandardScaler()
x_houses_train_scale = scales_x_houses.fit_transform(x_houses_train)
x_houses_test_scale = scales_x_houses.fit_transform(x_houses_test)
y_houses_train_scale = scales_x_houses.fit_transform(y_houses_train.reshape(-1,1))
y_houses_test_scale = scales_x_houses.fit_transform(y_houses_test.reshape(-1,1))

In [75]:
neural_network_houses = MLPRegressor(max_iter=1000, hidden_layer_sizes=(9,9))
neural_network_houses.fit(x_houses_train_scale,y_houses_train_scale.ravel())
neural_network_houses.score(x_houses_train_scale,y_houses_train_scale.ravel())


0.8892021714976956

In [76]:
neural_network_houses.score(x_houses_test_scale,y_houses_test_scale)

0.8677553823773082

In [77]:
predictions_house = neural_network_houses.predict(x_houses_test_scale)
predictions_house =predictions_house.reshape(-1,1)
predictions_house

array([[-0.09411028],
       [-0.35967954],
       [ 0.3951037 ],
       ...,
       [-0.619735  ],
       [ 5.45853285],
       [ 0.21987045]])

In [78]:
y_houses_test_scale

array([[-0.21938894],
       [-0.25482683],
       [ 1.29431529],
       ...,
       [-0.79905159],
       [ 2.87130146],
       [-0.63958108]])

In [79]:
y_houses_test_inverse = scaler_y.inverse_transform(y_houses_test)

In [80]:
predict_houses_inverse = scaler_y.inverse_transform(predictions_house)
predict_houses_inverse

array([[ 2275.28207574],
       [ 1514.16667123],
       [ 3677.35818283],
       ...,
       [  768.85364247],
       [18189.03040299],
       [ 3175.14367846]])

In [81]:
mean_absolute_error(y_houses_test_inverse,predict_houses_inverse)

1563881217.0145512