In [2]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from yellowbrick.regressor import ResidualsPlot

In [3]:
df_health_plan = pd.read_csv('../Bases de dados/plano_saude2.csv')
df_health_plan

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [4]:
x_health_plan=df_health_plan.iloc[:,0:1].values
x_health_plan

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [5]:
y_health_plan = df_health_plan.iloc[:,1].values
y_health_plan

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [6]:
polynomial = PolynomialFeatures(degree=4)
x_health_plan_poly = polynomial.fit_transform(x_health_plan)
x_health_plan_poly

array([[1.0000000e+00, 1.8000000e+01, 3.2400000e+02, 5.8320000e+03,
        1.0497600e+05],
       [1.0000000e+00, 2.3000000e+01, 5.2900000e+02, 1.2167000e+04,
        2.7984100e+05],
       [1.0000000e+00, 2.8000000e+01, 7.8400000e+02, 2.1952000e+04,
        6.1465600e+05],
       [1.0000000e+00, 3.3000000e+01, 1.0890000e+03, 3.5937000e+04,
        1.1859210e+06],
       [1.0000000e+00, 3.8000000e+01, 1.4440000e+03, 5.4872000e+04,
        2.0851360e+06],
       [1.0000000e+00, 4.3000000e+01, 1.8490000e+03, 7.9507000e+04,
        3.4188010e+06],
       [1.0000000e+00, 4.8000000e+01, 2.3040000e+03, 1.1059200e+05,
        5.3084160e+06],
       [1.0000000e+00, 5.3000000e+01, 2.8090000e+03, 1.4887700e+05,
        7.8904810e+06],
       [1.0000000e+00, 5.8000000e+01, 3.3640000e+03, 1.9511200e+05,
        1.1316496e+07],
       [1.0000000e+00, 6.3000000e+01, 3.9690000e+03, 2.5004700e+05,
        1.5752961e+07]])

In [7]:
x_health_plan_poly.shape

(10, 5)

In [8]:
regression_polinomial_health = LinearRegression()
regression_polinomial_health.fit(x_health_plan_poly,y_health_plan)

LinearRegression()

In [9]:
regression_polinomial_health.coef_

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [10]:
regression_polinomial_health.intercept_

16561.974637941225

In [11]:
new=[[40]]
new= polynomial.fit_transform(new)
predict_health = regression_polinomial_health.predict(new)
predict_health

array([1335.33958016])

In [12]:
predict_health = regression_polinomial_health.predict(x_health_plan_poly)
predict_health

array([ 549.65035466,  345.85081577,  616.53845994,  975.83915951,
       1249.06759854, 1472.72727271, 1894.51048941, 2973.29836768,
       5379.16083826, 9993.35664352])

In [13]:
grafic = px.scatter(x=df_health_plan.iloc[:,0],y=y_health_plan)
grafic.add_scatter(x=df_health_plan.iloc[:,0],y=predict_health,name='Regressin Poly health')
grafic

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'xaxis': 'x',
              'y': array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100, 10100],
                         dtype=int64),
              'yaxis': 'y'},
             {'name': 'Regressin Poly health',
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'y': array([ 549.65035466,  345.85081577,  616.53845994,  975.83915951,
                          1249.06759854, 1472.72727271, 1894.51048941, 2973.29836768,
                          5379.16083826, 9993.35664352])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'y'}}}
})

In [16]:
df_houses = pd.read_csv('../Bases de dados/house_prices.csv')
df_houses

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [24]:
x_houses = df_houses.iloc[:,3:19].values
y_houses = df_houses.iloc[:,2:3].values
x_houses.shape,y_houses.shape

((21613, 16), (21613, 1))

In [28]:
x_houses_train,x_houses_test,y_houses_train,y_houses_test = train_test_split(x_houses,y_houses,random_state=1,test_size=0.3)

In [29]:
x_houses_test.shape,y_houses_test.shape

((6484, 16), (6484, 1))

In [31]:
x_houses_train.shape,y_houses_train.shape

((15129, 16), (15129, 1))

In [33]:
polynomial_houses = PolynomialFeatures(degree=2)
x_houses_train_poly = polynomial_houses.fit_transform(x_houses_train)
x_houses_test_poly = polynomial_houses.transform(x_houses_test)

In [34]:
x_houses_train_poly.shape,x_houses_test_poly.shape

((15129, 153), (6484, 153))

In [35]:
regression_houses = LinearRegression()
regression_houses.fit(x_houses_train_poly,y_houses_train)
regression_houses.coef_, regression_houses.intercept_

(array([[ 1.10368990e+03,  1.64867610e+07, -1.47053414e+07,
         -4.56556139e+04,  2.38393331e+01, -3.32878665e+07,
          5.01065747e+07,  3.28228702e+06,  8.83131275e+06,
         -1.45644414e+07,  6.69181659e+04,  1.99577434e+04,
         -6.15720473e+04,  4.68681339e+04, -6.95591874e+05,
          1.10884692e+08, -7.71946079e+07,  1.04051491e+03,
          4.10846063e+03, -7.24906113e+01,  6.43365234e-02,
          1.84721932e+04, -7.00808858e+03,  8.53317588e+03,
         -6.03971957e+03,  3.61373518e+03,  4.58260935e+01,
          5.75697823e+01, -5.99282854e+01, -2.45356889e-01,
         -6.64002365e+01, -3.48063466e+04,  6.71735444e+04,
         -9.00890979e+03,  8.73273956e+00, -5.92900349e-02,
         -3.85926487e+04,  2.44629201e+04,  4.58255606e+02,
         -4.29765620e+03,  1.04553422e+04,  1.66835344e+01,
         -7.44225609e+00,  5.05938024e+02, -2.01584491e+01,
          2.01255709e+01,  6.57811808e+04, -7.03875591e+04,
         -5.18586284e+02,  7.53244924e+0

In [36]:
regression_houses.score(x_houses_train_poly,y_houses_train)

0.8120408413185275

In [37]:
regression_houses.score(x_houses_test_poly,y_houses_test)

0.8235833828099599

In [39]:
predict_house = regression_houses.predict(x_houses_test_poly)
predict_house

array([[ 562006.52900314],
       [ 487815.85347366],
       [ 567354.45035934],
       ...,
       [ 353992.10934067],
       [2770478.94865799],
       [ 420661.12348938]])

In [40]:
y_houses_test

array([[ 459000.],
       [ 445000.],
       [1057000.],
       ...,
       [ 230000.],
       [1680000.],
       [ 293000.]])

In [41]:
mean_absolute_error(y_houses_test,predict_house)

105291.77745758259

In [43]:
mean_squared_error(y_houses_test,predict_house)

27533397957.475903