In [26]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split
import seaborn as sns

In [27]:
df_health_plan = pd.read_csv('../Bases de dados/plano_saude2.csv')
df_health_plan

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [28]:
x_health_plan=df_health_plan.iloc[:,0:1].values
x_health_plan

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [29]:
y_health_plan = df_health_plan.iloc[:,1].values
y_health_plan

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [30]:
decision_tree_healt_plan = DecisionTreeRegressor()

In [31]:
decision_tree_healt_plan.fit(x_health_plan,y_health_plan)

DecisionTreeRegressor()

In [32]:
prediction_healt = decision_tree_healt_plan.predict(x_health_plan)
prediction_healt

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [33]:
y_health_plan

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [34]:
decision_tree_healt_plan.score(x_health_plan,y_health_plan)

1.0

In [35]:
grafic = px.scatter(x=x_health_plan.ravel(),y=y_health_plan)
grafic.add_scatter(x=x_health_plan.ravel(),y=prediction_healt,name='Regression Tree Health Plan')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'xaxis': 'x',
              'y': array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100, 10100],
                         dtype=int64),
              'yaxis': 'y'},
             {'name': 'Regression Tree Health Plan',
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'y': array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,  5100.,
                          10100.])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'y'}}}
})

In [36]:
x_test_tree = np.arange(min(x_health_plan),max(x_health_plan),step=0.1)
x_test_tree = x_test_tree.reshape(-1,1)
x_test_tree.shape

C:\Users\mbern\AppData\Local\Temp\ipykernel_15848\719874235.py:1: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



(450, 1)

In [37]:
grafic = px.scatter(x=x_health_plan.ravel(),y=y_health_plan)
grafic.add_scatter(x=x_test_tree.ravel(),y=decision_tree_healt_plan.predict(x_test_tree),name='Regression Tree Health Plan')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'xaxis': 'x',
              'y': array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100, 10100],
                         dtype=int64),
              'yaxis': 'y'},
             {'name': 'Regression Tree Health Plan',
              'type': 'scatter',
              'x': array([18. , 18.1, 18.2, ..., 62.7, 62.8, 62.9]),
              'y': array([  470.,   470.,   470., ..., 10100., 10100., 10100.])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'y'}}}
})

In [38]:
predict_test = decision_tree_healt_plan.predict([[40]])
predict_test

array([1150.])

In [39]:
df_houses = pd.read_csv('../Bases de dados/house_prices.csv')
df_houses

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [40]:
x_houses = df_houses.iloc[:,3:19].values
y_houses = df_houses.iloc[:,2:3].values
x_houses.shape,y_houses.shape

((21613, 16), (21613, 1))

In [41]:
x_houses_train,x_houses_test,y_houses_train,y_houses_test = train_test_split(x_houses,y_houses,random_state=1,test_size=0.3)

In [42]:
regression_tree_houses = DecisionTreeRegressor()

In [43]:
regression_tree_houses.fit(x_houses_train,y_houses_train)

DecisionTreeRegressor()

In [45]:
prediction_houses = regression_tree_houses.predict(x_houses_test)

In [48]:
regression_tree_houses.score(x_houses_test,y_houses_test)

0.7820417073654403

In [49]:
regression_tree_houses.score(x_houses_train,y_houses_train)

0.999326695553979

In [51]:
mean_absolute_error(y_houses_test,prediction_houses)

99244.79804133251

In [52]:
mean_squared_error(y_houses_test,prediction_houses)

34016820551.403957