In [16]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [17]:
df_health_plan = pd.read_csv('../Bases de dados/plano_saude2.csv')
x_health_plan=df_health_plan.iloc[:,0:1].values
y_health_plan=df_health_plan.iloc[:,1].values

Kernel Linear

In [18]:
svm_health_plan = SVR(kernel='linear')
svm_health_plan.fit(x_health_plan,y_health_plan)
svm_health_plan.score(x_health_plan,y_health_plan)

0.294299767185203

In [19]:
grafic = px.scatter(x=x_health_plan.ravel(),y=y_health_plan)
grafic.add_scatter(x=x_health_plan.ravel(),y=svm_health_plan.predict(x_health_plan),name='SVM  Regression Health Plan')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'xaxis': 'x',
              'y': array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100, 10100],
                         dtype=int64),
              'yaxis': 'y'},
             {'name': 'SVM  Regression Health Plan',
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'y': array([ 216.14,  520.1 ,  824.06, 1128.02, 1431.98, 1735.94, 2039.9 , 2343.86,
                          2647.82, 2951.78])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'y'}}}
})

Kernel Poly


In [20]:
svm_health_plan = SVR(kernel='poly',degree=3)

In [21]:
svm_health_plan.fit(x_health_plan,y_health_plan)
svm_health_plan.score(x_health_plan,y_health_plan)

0.6697433307984383

In [22]:
grafic = px.scatter(x=x_health_plan.ravel(),y=y_health_plan)
grafic.add_scatter(x=x_health_plan.ravel(),y=svm_health_plan.predict(x_health_plan),name='SVM  Regression Health Plan')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'xaxis': 'x',
              'y': array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100, 10100],
                         dtype=int64),
              'yaxis': 'y'},
             {'name': 'SVM  Regression Health Plan',
              'type': 'scatter',
              'x': array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64),
              'y': array([ 318.7144702 ,  441.00729174,  629.89999243,  899.87080684,
                          1265.39796958, 1740.95971524, 2341.03427842, 3080.09989371,
                          3972.6347957 , 5033.11721899])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'y'}}}
})

Kernel  RBF

In [23]:
scaler_x = StandardScaler()
scaler_y = StandardScaler()
x_scaler = scaler_x.fit_transform(x_health_plan)
y_scaler = scaler_y.fit_transform(y_health_plan.reshape(-1,1))
svm_health_plan = SVR(kernel='rbf')
x_scaler,y_scaler

(array([[-1.5666989 ],
        [-1.21854359],
        [-0.87038828],
        [-0.52223297],
        [-0.17407766],
        [ 0.17407766],
        [ 0.52223297],
        [ 0.87038828],
        [ 1.21854359],
        [ 1.5666989 ]]),
 array([[-0.72401136],
        [-0.7065653 ],
        [-0.66818397],
        [-0.59839975],
        [-0.48674498],
        [-0.35415495],
        [-0.17620517],
        [ 0.18667281],
        [ 0.8914935 ],
        [ 2.63609918]]))

In [24]:
svm_health_plan.fit(x_scaler,y_scaler)
svm_health_plan.score(x_scaler,y_scaler.ravel())

c:\Users\mbern\OneDrive\machineLearningCourse\courseMachineLearning\.venv\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



0.7561578176049305

In [25]:
grafic = px.scatter(x=x_scaler.ravel(),y=y_scaler.ravel())
grafic.add_scatter(x=x_scaler.ravel(),y=svm_health_plan.predict(x_scaler),name='SVM  Regression Health Plan')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
                           0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ]),
              'xaxis': 'x',
              'y': array([-0.72401136, -0.7065653 , -0.66818397, -0.59839975, -0.48674498,
                          -0.35415495, -0.17620517,  0.18667281,  0.8914935 ,  2.63609918]),
              'yaxis': 'y'},
             {'name': 'SVM  Regression Health Plan',
              'type': 'scatter',
              'x': array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
                           0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ]),
              'y': array([-0.62348071, -0.63291278, -0.57066507, -0.49866508, -0.44637596,
                          -0.36326797, -0.13553889,  0.29353246,  0.79122818,  1.09382968])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'y'}}}
})

In [26]:
new =[[40]]
new = scaler_x.transform(new)
predict_health = svm_health_plan.predict(new)
scaler_y.inverse_transform(predict_health.reshape(1,-1))

array([[1333.85650748]])

House Data

In [27]:
df_houses = pd.read_csv('../Bases de dados/house_prices.csv')
x_houses = df_houses.iloc[:,3:19].values
y_houses = df_houses.iloc[:,2:3].values

In [28]:
x_houses_train,x_houses_test,y_houses_train,y_houses_test = train_test_split(x_houses,y_houses,random_state=1,test_size=0.3)

In [30]:
scales_x_houses = StandardScaler()
scales_y_houses = StandardScaler()
x_houses_train_scale = scales_x_houses.fit_transform(x_houses_train)
x_houses_test_scale = scales_x_houses.fit_transform(x_houses_test)
y_houses_train_scale = scales_x_houses.fit_transform(y_houses_train.reshape(-1,1))
y_houses_test_scale = scales_x_houses.fit_transform(y_houses_test.reshape(-1,1))

In [32]:
regression_svm_houses = SVR(kernel='rbf')
regression_svm_houses.fit(x_houses_train_scale,y_houses_train_scale.ravel())

SVR()

In [33]:
regression_svm_houses.score(x_houses_train_scale,y_houses_train_scale)

0.8261253972988803

In [34]:
regression_svm_houses.score(x_houses_test_scale,y_houses_test_scale)

0.7062107093923877

In [37]:
predict_houses = regression_svm_houses.predict(x_houses_test_scale)
predict_houses

array([-0.17149556, -0.27938668,  0.23043063, ..., -0.61666415,
        3.63549185,  0.09035064])

In [38]:
y_houses_test_scale

array([[-0.21938894],
       [-0.25482683],
       [ 1.29431529],
       ...,
       [-0.79905159],
       [ 2.87130146],
       [-0.63958108]])

In [42]:
y_houses_inverse = scaler_y.inverse_transform(y_houses_test_scale)
predict_houses_inverse = scaler_y.inverse_transform(predict_houses.reshape(-1,1))

In [43]:
y_houses_inverse

array([[ 1916.23631387],
       [ 1814.67212659],
       [ 6254.47802802],
       ...,
       [  254.93639324],
       [10774.08436233],
       [  711.97523603]])

In [44]:
predict_houses_inverse

array([[ 2053.49765208],
       [ 1744.28417061],
       [ 3205.40892882],
       ...,
       [  777.65463578],
       [12964.23655636],
       [ 2803.94286665]])

In [45]:
from sklearn.metrics import mean_absolute_error

In [46]:
mean_absolute_error(y_houses_inverse,predict_houses_inverse)

653.8121802500185